#ifndef _MODO_BOARD_CONFIG_H_
#define _MODO_BOARD_CONFIG_H_
//modonut
#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_DEFAULT_OUTPUT_VOLUME 100

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_48
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_5
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_47

// 功放控制引脚
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_15
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_42
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_41
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

// 按键配置
#define BOOT_BUTTON_GPIO        GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_2
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_1

// WS2812 LED配置
#define WS2812_GPIO             GPIO_NUM_7
#define WS2812_LED_COUNT        7
#define BATTERY_LED_GPIO        GPIO_NUM_6

// FM175XX NFC配置
#define FM175XX_SCK  GPIO_NUM_11
#define FM175XX_MISO GPIO_NUM_13
#define FM175XX_MOSI GPIO_NUM_12
#define FM175XX_CS   GPIO_NUM_10
#define FM175XX_NPD  GPIO_NUM_0

// 离线语音唤醒串口通讯
#define VOICE_UART_TXD       GPIO_NUM_43
#define VOICE_UART_RXD       GPIO_NUM_44

// AXP2101电源管理配置
#define AXP2101_I2C_PORT        I2C_NUM_0
#define AXP2101_GPIO_SDA        GPIO_NUM_42
#define AXP2101_GPIO_SCL        GPIO_NUM_41
#define AXP2101_I2C_ADDR        0x34

#endif // _MODO_BOARD_CONFIG_H_ 