#ifndef _MODO_BOARD_CONFIG_H_
#define _MODO_BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_DEFAULT_OUTPUT_VOLUME 100

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_2
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_47
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_16
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_15

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

// 按键配置
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_40
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

// WS2812 LED配置
#define WS2812_GPIO             GPIO_NUM_48
#define WS2812_LED_COUNT        8

// RC522 NFC配置
#define RC522_SPI_HOST          SPI2_HOST
#define RC522_GPIO_MISO         GPIO_NUM_13
#define RC522_GPIO_MOSI         GPIO_NUM_11
#define RC522_GPIO_SCLK         GPIO_NUM_12
#define RC522_GPIO_CS           GPIO_NUM_10
#define RC522_GPIO_RST          GPIO_NUM_9

// AXP2101电源管理配置
#define AXP2101_I2C_PORT        I2C_NUM_0
#define AXP2101_GPIO_SDA        GPIO_NUM_41
#define AXP2101_GPIO_SCL        GPIO_NUM_42
#define AXP2101_I2C_ADDR        0x36

// 其他GPIO配置
#define BUILTIN_LED_GPIO        GPIO_NUM_6

#endif // _MODO_BOARD_CONFIG_H_ 